### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by shu-matsu09** [shu-matsu09/protospace-33356#1]
# URL
https://protospace-33356.herokuapp.com/

**Comment by MakiTaka** [comment]
@shu-matsu09 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
**・現状、他のユーザーでログインした状態で、直接編集ページのURLを入力すると編集ページに遷移し、変更できてしまいます。**
※ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとするとトップページにリダイレクトされるように実装しましょう


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shu-matsu09** [comment]
[修正箇所]
・他のユーザーでログインした状態で、直接編集ページのURLを入力すると編集ページに遷移し、変更できてしまう点を修正しました。
ご確認をよろしくお願いいたします。

# URL
https://protospace-33356.herokuapp.com/

**Comment by MakiTaka** [comment]
@shu-matsu09 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
